version: "3"
services:
    m2-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: m2-fpm-service
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/config/php-fpm/conf.d/m2.conf:/usr/local/etc/php-fpm.d/m2.conf
            - ./docker/config/php-fpm/m2.ini:/usr/local/etc/php/conf.d/m2.ini
        depends_on:
            - m2-db
            - m2-redis
        networks:
            - m2
    m2-webserver:
        image: nginx:alpine
        working_dir: /var/www/html/m2
        ports:
            - "8089:80"
        volumes:
            - ./m2:/var/www/html/m2
            - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - m2-app
        networks:
            - m2
    m2-db:
        image: mariadb
        container_name: m2-db-service
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./docker/config/mysql:/docker-entrypoint-initdb.d
            - m2-dbdata:/var/lib/mysql
        networks:
            - m2
    m2-varnish:
        image: varnish:6
        container_name: m2-varnish-service
        volumes:
            - ./docker/config/varnish/default.vcl:/etc/varnish/default.vcl
        ports:
            - "8011:80"
    m2-redis:
        image: redis
        container_name: m2-redis-service
        expose:
            - "6379"
        networks:
            - m2
    m2-adminer:
        image: adminer
        volumes:
            - ./docker/config/adminer/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
        ports:
            - "8088:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql
            ADMINER_DESIGN: "flat"
        networks:
            - m2
        depends_on:
            - m2-db
networks:
    m2:
        external: true
volumes:
  m2-dbdata: